version: '3'
services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: jenkins
        privileged: true
        user: root
        ports:
            - 9091:8080            
            - 50000:50000
        volumes:
            - ./data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DOCKER_HOST=unix:///var/run/docker.sock

    agent:
        build: jenkins-agent
        container_name: agent
        privileged: true
        user: root
        ports:
            - 22:22         ## jenkins ssh port
            - 9001:9100     ## prometheus-node-exporter port 
        volumes:
            - ./jenkins-agent/ssh/jenkins-agent.pub:/home/jenkins/.ssh/authorized_keys
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DOCKER_HOST=unix:///var/run/docker.sock
